// wb-demo runner — the BL-004 money shot as a pass/fail pair.
//
//   node server/wb/run-wb-demo.mjs
//
// Reads samples/wb-demo/assembly.json, synthesizes the ballast block STL
// (documented: code-built box, not an API export — rebuilds offline byte
// for byte), computes assembly weight & balance twice — once as declared
// (must PASS the armed CG window) and once with the ballast slid outboard
// (must be REFUSED by CgWindowError) — and writes both reports next to the
// assembly spec. Exits nonzero unless the pair behaves exactly that way.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
import { assemblyWB, CgWindowError, WB_DISCLAIMERS } from "./wb.mjs";
import { boxStl } from "./box-stl.mjs";

const ROOT = fileURLToPath(new URL("../../", import.meta.url));
const DEMO_DIR = join(ROOT, "samples/wb-demo");
const TOOL = "server/wb/run-wb-demo.mjs (BL-004)";

const spec = JSON.parse(readFileSync(join(DEMO_DIR, "assembly.json"), "utf8"));

// Ballast: 20 x 20 x 10 mm box, footprint centered on its own origin so the
// declared position reads as "block center at x". Deterministic bytes.
mkdirSync(DEMO_DIR, { recursive: true });
writeFileSync(join(DEMO_DIR, "ballast.stl"), boxStl({ sizeMm: [20, 20, 10], cornerMm: [-10, -10, 0] }));

const loadParts = (positions = {}) =>
  spec.parts.map((p) => ({
    name: p.name,
    stl: readFileSync(join(ROOT, p.stlPath)),
    densityKgM3: p.densityKgM3,
    ...(p.measuredMassG !== undefined && { measuredMassG: p.measuredMassG }),
    positionMm: positions[p.name] ?? p.positionMm,
  }));

const fmt = (n, d = 3) => {
  const s = Number(n).toFixed(d);
  return s === `-${(0).toFixed(d)}` ? (0).toFixed(d) : s; // no cosmetic −0.000
};
const vec = (v) => `[${v.map((n) => fmt(n)).join(", ")}]`;

// Verbatim from docs/backlog/BL-004-weight-and-balance.md — Honest boundaries.
const HONEST_BOUNDARIES = `1. Modeled mass is solid/nominal; printed mass depends on infill + filament density.
   **Calibration hook is first-class:** a part's \`measuredMassG\` (operator's scale)
   overrides modeled mass, and the report states which basis each part used.
2. **This is mass and a balance point, nothing else.** It says nothing about whether
   the assembly is strong enough, stiff enough, or safe to use. Mass, balance point
   and (stretch) inertia only.`;

function partRows(wb, positions = {}) {
  const lines = [
    "| part | basis | mass (g) | modeled (g) | measured (g) | volume (mm³) | position (mm) | part CG, assembly frame (mm) |",
    "|---|---|---|---|---|---|---|---|",
  ];
  for (const [i, p] of wb.perPart.entries()) {
    const declared = positions[p.name] ?? spec.parts[i].positionMm;
    lines.push(
      `| ${p.name} | ${p.basis} | ${fmt(p.massG)} | ${p.modeledMassG !== undefined ? fmt(p.modeledMassG) : "—"} | ` +
        `${p.measuredMassG !== undefined ? fmt(p.measuredMassG) : "—"} | ${fmt(p.volumeMm3, 1)} | ` +
        `${vec(declared)} | ${vec(p.cgMm)} |`,
    );
  }
  return lines.join("\n");
}

function reportMd({ title, wb, gate, positions }) {
  const w = spec.cgWindow;
  return `# ${title}

Generated by \`${TOOL}\` on ${new Date().toISOString()} — advisory, flags only, certifies nothing.

Assembly: **${spec.assembly}**
Frame: ${spec.frame}
Ballast source: \`samples/wb-demo/ballast.stl\` is synthesized in code (deterministic 12-triangle
box via \`server/wb/box-stl.mjs\`), not an API export — documented per BL-004.

## Per-part weight & balance

${partRows(wb, positions)}

## Totals

- **Total mass: ${fmt(wb.totalMassG)} g**
- **Combined CG: ${vec(wb.cgMm)} mm** (assembly frame)

## CG window gate

Armed window: axis **${w.axis}**, [${fmt(w.minMm, 1)}, ${fmt(w.maxMm, 1)}] mm.

${gate.result === "PASS"
    ? `Combined CG on ${w.axis} = **${fmt(gate.cgOnAxisMm)} mm** → **PASS** (inside the window).`
    : `Combined CG on ${w.axis} = **${fmt(gate.cgOnAxisMm)} mm** → **FAIL — report refused.**

\`\`\`
${gate.error.name}: ${gate.error.message}
\`\`\`

The gate is fail-closed: \`assemblyWB\` throws \`CgWindowError\` — there is no report object to
ship. What that refuses is this report and nothing else: \`server/wb/\` is a standalone tool,
off the \`npm run demo\` path, so no job, no package and no ledger row is involved. The rows
above come from the same assembly computed WITHOUT the window armed, shown here so the
operator can see how far out the CG landed.`}

## Honest boundaries (verbatim from BL-004)

${HONEST_BOUNDARIES}

## Basis notes

${spec.parts.map((p) => `- **${p.name}** — density ${p.densityKgM3} kg/m³${p.densityNote ? ` (${p.densityNote})` : ""}${p.measuredMassG !== undefined ? `; measuredMassG ${p.measuredMassG} g${p.measuredNote ? ` (${p.measuredNote})` : ""}` : ""}${p.positionNote ? `; position: ${p.positionNote}` : ""}`).join("\n")}

## Disclaimers

${WB_DISCLAIMERS.map((d) => `- ${d}`).join("\n")}
`;
}

const reportJson = ({ scenario, wb, gate, positions }) => ({
  generated: new Date().toISOString(),
  tool: TOOL,
  assembly: spec.assembly,
  scenario,
  frame: spec.frame,
  cgWindow: spec.cgWindow,
  gate,
  totalMassG: wb.totalMassG,
  cgMm: wb.cgMm,
  perPart: wb.perPart.map((p, i) => ({ ...p, positionMm: positions[p.name] ?? spec.parts[i].positionMm })),
  disclaimers: WB_DISCLAIMERS,
});

// ---- scenario 1: as declared — must PASS the armed window -------------------

let pass;
try {
  pass = assemblyWB(loadParts(), { cgWindow: spec.cgWindow });
} catch (e) {
  console.error(`wb-demo: declared assembly must PASS its own window, got: ${e.message}`);
  process.exit(1);
}
writeFileSync(
  join(DEMO_DIR, "wb-report.json"),
  JSON.stringify(reportJson({ scenario: "as declared", wb: pass, gate: pass.window, positions: {} }), null, 2) + "\n",
);
writeFileSync(
  join(DEMO_DIR, "wb-report.md"),
  reportMd({ title: "Weight & balance — wb-demo (as declared): PASS", wb: pass, gate: pass.window, positions: {} }),
);
console.log(`PASS  total ${fmt(pass.totalMassG)} g, CG ${vec(pass.cgMm)} mm, ` +
  `${spec.cgWindow.axis} = ${fmt(pass.window.cgOnAxisMm)} in [${spec.cgWindow.minMm}, ${spec.cgWindow.maxMm}]`);

// ---- scenario 2: ballast slid outboard — the gate must refuse ----------------

const shiftedPositions = { [spec.shifted.part]: spec.shifted.positionMm };
let refused = null;
try {
  assemblyWB(loadParts(shiftedPositions), { cgWindow: spec.cgWindow });
  console.error("wb-demo: shifted assembly was NOT refused — the gate is broken");
  process.exit(1);
} catch (e) {
  if (!(e instanceof CgWindowError)) throw e;
  refused = e;
}
// Same assembly without the window, so the FAIL report can show the numbers.
const shifted = assemblyWB(loadParts(shiftedPositions));
const failGate = {
  result: "FAIL",
  cgOnAxisMm: refused.cgOnAxisMm,
  error: { name: refused.name, code: refused.code, message: refused.message,
    axis: refused.axis, minMm: refused.minMm, maxMm: refused.maxMm },
};
writeFileSync(
  join(DEMO_DIR, "wb-report-shifted-fail.json"),
  JSON.stringify(reportJson({ scenario: `ballast moved to ${vec(spec.shifted.positionMm)} — ${spec.shifted.note}`,
    wb: shifted, gate: failGate, positions: shiftedPositions }), null, 2) + "\n",
);
writeFileSync(
  join(DEMO_DIR, "wb-report-shifted-fail.md"),
  reportMd({ title: "Weight & balance — wb-demo (ballast moved): REFUSED", wb: shifted, gate: failGate,
    positions: shiftedPositions }),
);
console.log(`FAIL  (as designed) ${refused.message}`);
console.log(`Reports written to samples/wb-demo/`);
